# mpvExtended English Learning configuration

hwdec=auto-safe
save-position-on-quit=yes
keep-open=yes

sub-auto=fuzzy
sub-visibility=no

script=/sdcard/Android/media/app.marlboroadvance.mpvex/english-subs-android.lua

alang=ja,jpn,en,eng
slang=en,eng,ja,jpn
